import 'package:photoroomapp/shared/constants/app_assets.dart';

List<Map> onboardingImagesList = [
  {
    "image": AppAssets.Onboarding3,
    "text": "Unleash your Creativity with Image reference "
  },
  {
    "image": AppAssets.Onboarding2,
    "text": "Create Realistic High Quality Imagery "
  },
  {"image": AppAssets.Onboarding1, "text": "Bring your Ideas to Life with AI"},
];

List<Map> artsStyleImagesLIst = [
  {"image": "", "id": "0"},
  {"image": AppAssets.artstyle1, "id": "1"},
  {"image": AppAssets.artstyle2, "id": "2"},
  {"image": AppAssets.artstyle3, "id": "3"},
  {"image": AppAssets.artstyle4, "id": "4"},
  {"image": AppAssets.artstyle1, "id": "1"},
  {"image": AppAssets.artstyle2, "id": "1"},
];

List<Map> filterResult = [
  {"title": "Trending Creations", "icon": AppAssets.trendingicon},
  {"title": "Anime", "icon": AppAssets.animeicon},
  {"title": "Photography", "icon": AppAssets.photography},
  {"title": "Architecture", "icon": AppAssets.architectureicon},
  {"title": "TSci-fi", "icon": AppAssets.scifiicon},
  {"title": "Food", "icon": AppAssets.foodicon},
  {"title": "Character", "icon": AppAssets.charatericon},
  {"title": "Trending Artstyle", "icon": AppAssets.starticon},
];

List<Map<String, String>> freePikStyles = [
  {"title": "photo", "icon": AppAssets.photo},
  {"title": "cartoon", "icon": AppAssets.cartoon},
  {"title": "3d", "icon": AppAssets.threeD},
  {"title": "vector", "icon": AppAssets.vector},
  {"title": "vintage", "icon": AppAssets.vintage},
  {"title": "digital-art", "icon": AppAssets.digitalart},
  {"title": "pixel-art", "icon": AppAssets.pixelart},
  {"title": "70s-vibe", "icon": AppAssets.seventyVibe},
  {"title": "comic", "icon": AppAssets.comic},
  {"title": "painting", "icon": AppAssets.painting},
  {"title": "dark", "icon": AppAssets.dark},
  {"title": "art-nouveau", "icon": AppAssets.photo},
  {"title": "sketch", "icon": AppAssets.sketch},
  {"title": "mockup", "icon": AppAssets.mockup},
  {"title": "cyberpunk", "icon": AppAssets.cyberpunk},
  {"title": "anime", "icon": AppAssets.anime},
  {"title": "watercolor", "icon": AppAssets.watercolor},
  {"title": "origami", "icon": AppAssets.origami},
  {"title": "surreal", "icon": AppAssets.surreal},
  {"title": "fantasy", "icon": AppAssets.fantasy},
  {"title": "traditional-japan", "icon": AppAssets.traditionalJapan},
  {"title": "studio-shot", "icon": AppAssets.studio},
];

List<Map<String, dynamic>> reportOptions = [
  {"id": "1", "title": "Inappropriate Content (e.g., nudity, violence)"},
  {"id": "2", "title": "Misleading or False Information"},
  {"id": "3", "title": "Copyright Violation"},
  {"id": "4", "title": "Low-Quality or Corrupted Image"},
  {"id": "5", "title": "Other ( Please Specify)"},
];

final List<String> sexualWordsList = [
  // Basic sexual words
  "sex",
  "sexual",
  "sexuality",
  "sexy",
  "xxx",
  "nude",
  "nudes",
  "naked",
  "porn",
  "pornhub",
  "xnxx",
  "xxxvideos",
  "erotic",
  "erotica",
  "sensual",
  "provocative",

  // Body parts / slang
  "boobs",
  "breasts",
  "nipples",
  "nipple",
  "penis",
  "dick",
  "cock",
  "pussy",
  "vagina",
  "vag",
  "clit",
  "butt",
  "booty",
  "ass",
  "arse",
  "anal",
  "anus",
  "bum",
  "bums",
  "thighs",
  "balls",
  "scrotum",
  "testicles",
  "tits",
  "tit",
  "hooter",
  "hooters",
  "privates",
  "genitals",
  "crotch",

  // Sexual acts / descriptions
  "masturbation",
  "masturbate",
  "fingering",
  "blowjob",
  "bj",
  "handjob",
  "hj",
  "cum",
  "cumming",
  "ejaculate",
  "ejaculation",
  "orgasm",
  "deepthroat",
  "coitus",
  "penetration",
  "humping",
  "grinding",
  "squirting",
  "moaning",
  "kissing",
  "foreplay",
  "seduction",
  "sensuality",
  "tease",
  "lust",
  "aroused",
  "arousal",
  "hooking up",

  // Common slang / synonyms
  "fap",
  "fapping",
  "kink",
  "kinky",
  "bdsm",
  "bondage",
  "dominatrix",
  "dominant",
  "submissive",
  "sub",
  "dom",
  "roleplay",
  "role-play",
  "fetish",
  "fetishes",
  "spanking",
  "tickling",

  // Sexual services / references
  "escort",
  "camgirl",
  "cam-boy",
  "prostitute",
  "prostitution",
  "hooker",
  "stripper",
  "stripclub",
  "strip club",
  "sugarbaby",
  "sugardaddy",
  "sugar daddy",
  "sugar baby",
  "onlyfans",
  "fansly",

  // Porn categories / related
  "nsfw",
  "hardcore",
  "softcore",
  "adult",
  "adultwork",
  "milf",
  "teen",
  "stepmom",
  "stepsis",
  "stepbro",
  "incest",
  "taboo",
  "interracial",
  "bbw",
  "creampie",
  "gangbang",
  "facial",

  // Potential additional explicit slang
  "fleshlight",
  "dildo",
  "vibrator",
  "buttplug",
  "butt plug",
  "strapon",
  "strap-on",
  "oral",
  "oralsex",
  "doggystyle",
  "doggy style",
  "cowgirl",
  "reverse cowgirl",
  "missionary",
  "69",
  "sixtynine",
  "lingerie",
  "latex",
  "sex toys",
  "bondage gear",

  // Potential abbreviations or short forms
  "ffs", // (context-dependent)
  "bikini",
  "panties",
  "penty",
  "thong",
  "g-string",
  "bra",
  "stockings",
  "heels",
  "fishnets",
  "strip",
];
