// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG6CIzTm7L5ZlgRK1g-7DsIH2icuGin7c',
    appId: '1:586272014422:web:84793bfaff3e0312b67bf7',
    messagingSenderId: '586272014422',
    projectId: 'artleap-d2079',
    authDomain: 'artleap-d2079.firebaseapp.com',
    storageBucket: 'artleap-d2079.firebasestorage.app',
    measurementId: 'G-TKH4Z1WF6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALpDsstpx5oCzLUOFN0qL5UZ-6rHwe1Fw',
    appId: '1:586272014422:android:264bfdc71a13f633b67bf7',
    messagingSenderId: '586272014422',
    projectId: 'artleap-d2079',
    storageBucket: 'artleap-d2079.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAftafQlwY315UhnG63PTx9fwfnc0KEGfE',
    appId: '1:586272014422:ios:7a5a8f47c0903e34b67bf7',
    messagingSenderId: '586272014422',
    projectId: 'artleap-d2079',
    storageBucket: 'artleap-d2079.firebasestorage.app',
    iosBundleId: 'com.XrDIgital.ImaginaryVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAftafQlwY315UhnG63PTx9fwfnc0KEGfE',
    appId: '1:586272014422:ios:7a5a8f47c0903e34b67bf7',
    messagingSenderId: '586272014422',
    projectId: 'artleap-d2079',
    storageBucket: 'artleap-d2079.firebasestorage.app',
    iosBundleId: 'com.XrDIgital.ImaginaryVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG6CIzTm7L5ZlgRK1g-7DsIH2icuGin7c',
    appId: '1:586272014422:web:4f91ed94bc37227eb67bf7',
    messagingSenderId: '586272014422',
    projectId: 'artleap-d2079',
    authDomain: 'artleap-d2079.firebaseapp.com',
    storageBucket: 'artleap-d2079.firebasestorage.app',
    measurementId: 'G-RL1LVJY8JB',
  );

}