// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9fL968C_2bwJxEpZXLnttwD5b0aUm4cs',
    appId: '1:53715181958:web:01ba619a74b9a8fedecc07',
    messagingSenderId: '53715181958',
    projectId: 'imaginary-verse',
    authDomain: 'imaginary-verse.firebaseapp.com',
    storageBucket: 'imaginary-verse.appspot.com',
    measurementId: 'G-51WRG0TSJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzP6AwdJpE42SyOD7zTUKzIql4ht5-_w0',
    appId: '1:53715181958:android:834370fdc2bfa178decc07',
    messagingSenderId: '53715181958',
    projectId: 'imaginary-verse',
    storageBucket: 'imaginary-verse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCefdd4vFs6Va_9MR_Wf4BnX6jLdBbann4',
    appId: '1:53715181958:ios:263529af0cb3ab67decc07',
    messagingSenderId: '53715181958',
    projectId: 'imaginary-verse',
    storageBucket: 'imaginary-verse.appspot.com',
    iosClientId: '53715181958-361gee210cte31l49knhfa3clgc12hl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.imaginaryverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCefdd4vFs6Va_9MR_Wf4BnX6jLdBbann4',
    appId: '1:53715181958:ios:263529af0cb3ab67decc07',
    messagingSenderId: '53715181958',
    projectId: 'imaginary-verse',
    storageBucket: 'imaginary-verse.appspot.com',
    iosClientId: '53715181958-361gee210cte31l49knhfa3clgc12hl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.imaginaryverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9fL968C_2bwJxEpZXLnttwD5b0aUm4cs',
    appId: '1:53715181958:web:e35e769335a3721cdecc07',
    messagingSenderId: '53715181958',
    projectId: 'imaginary-verse',
    authDomain: 'imaginary-verse.firebaseapp.com',
    storageBucket: 'imaginary-verse.appspot.com',
    measurementId: 'G-E5T9SHX8H6',
  );
}
