import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:get_it/get_it.dart';
import 'package:photoroomapp/domain/api_repos_abstract/favourite_repo.dart';
import 'package:photoroomapp/domain/api_repos_abstract/freepik_ai_gen_repo.dart';
import 'package:photoroomapp/domain/api_repos_abstract/generate_image_repo.dart';
import 'package:photoroomapp/domain/api_repos_abstract/home_repo.dart';
import 'package:photoroomapp/domain/api_repos_abstract/img2img_repo.dart';
import 'package:photoroomapp/domain/api_repos_abstract/load_models_list_repo.dart';
import 'package:photoroomapp/domain/api_repos_abstract/reqres_repo.dart';
import 'package:photoroomapp/domain/api_repos_abstract/user_profile_repo.dart';
import 'package:photoroomapp/domain/api_repos_impl/favourite_repo_impl.dart';
import 'package:photoroomapp/domain/api_repos_impl/freepik_ai_gen_impl.dart';
import 'package:photoroomapp/domain/api_repos_impl/generate_image_repo_impl.dart';
import 'package:photoroomapp/domain/api_repos_impl/home_repo_impl.dart';
import 'package:photoroomapp/domain/api_repos_impl/img2img_repo_impl.dart';
import 'package:photoroomapp/domain/api_repos_impl/load_models_list_impl.dart';
import 'package:photoroomapp/domain/api_repos_impl/reqres_repo_impl.dart';
import 'package:photoroomapp/domain/api_repos_impl/user_profile_impl.dart';

mixin BaseRepo {
  // final DummyRepo _dummyRepo = DummyRepoImpl();
  // DummyRepo get dummyRepo => _dummyRepo;
  final ReqResRepo _reqresRepo = ReqResRepoImpl();
  ReqResRepo get reqresRepo => _reqresRepo;
  final GenerateImageRepo _generateImageRepo = GenerateImageImpl();
  GenerateImageRepo get generateImageRepo => _generateImageRepo;
  final GenerateImg2ImgRepo _generateImgToImgRepo = GenerateImg2ImgImpl();
  GenerateImg2ImgRepo get generateImgToImgRepo => _generateImgToImgRepo;
  final LoadModelsListRepo _modelsListRepo = LoadModelsListImpl();
  LoadModelsListRepo get modelListRepo => _modelsListRepo;
  final UserProfileRepo _userProfileRepo = UserProfileImpl();
  UserProfileRepo get userProfileRepo => _userProfileRepo;
  final FavouritRepo _favouriteRepo = FavouriteRepoImpl();
  FavouritRepo get favouriteRepo => _favouriteRepo;
  final HomeRepo _homeRepo = HomeRepoImpl();
  HomeRepo get homeRepo => _homeRepo;
  final FreepikAiGenRepo _freePikRepo = FreepikAiGenImpl();
  FreepikAiGenRepo get freePikRepo => _freePikRepo;
  final FirebaseFirestore firestore = GetIt.instance.get<FirebaseFirestore>();
}
